# this yml file is to create new VPC  into my AWS account.
Description: >
    Mohamed Dabo / Udacity
    This template deploys a VPC.
Resources:
    UdacityVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsHostnames: true
        Tags:
        - Key: name
          Value: myfirsttestvpc
